### ISSUE TITLE
Markdown takes a while to render and it looks ugly

### ISSUE THREAD

**Issue by potatoeggy** [BayviewComputerClub/smoothie-web#11]
**Describe the bug**
When first loading a problem page, markdown is visible for about half a second before it renders to HTML.

**To Reproduce**
1. Visit any problem page, e.g., http://smoothie.bayview.club/problem/bsspc2019p7

**Expected behavior**
The text does not change after initially shown to the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/25178974/74595687-90f79700-5012-11ea-81c0-9c4e1d6c8179.png)

**Additional context**
None

**Comment by potatoeggy** [comment]
You can actually notice this happening on all smoothie-web pages, not just problem ones

**Comment by espidev** [comment]
yes the latex loads after the page is finished loading
should probably hide it
