### ISSUE TITLE
[BUG] Inconsistency in problem-writing headers

### ISSUE THREAD

**Issue by potatoeggy** [BayviewComputerClub/smoothie-web#12]
**Describe the bug**
In http://smoothie.bayview.club/problem/bsspc2019p7, subtasks are under "Constraints", which is directly under the problem statement. Also, there is no space between "Subtasks" and "[X0%]"

In http://smoothie.bayview.club/problem/bsspc2019p5, subtasks are under "Subtasks", which uses a different header style than "Constraints", and is under the output specification. 

**To Reproduce**
1. Visit http://smoothie.bayview.club/problem/bsspc2019p7
2. Visit http://smoothie.bayview.club/problem/bsspc2019p5
3. Realise OCD is triggered

**Expected behavior**
They should look the same.

**Screenshots**
![image](https://user-images.githubusercontent.com/25178974/74595741-39a5f680-5013-11ea-82a1-7d4da28401ea.png)
![image](https://user-images.githubusercontent.com/25178974/74595743-43c7f500-5013-11ea-98c1-b67febfd0a9a.png)

**Comment by espidev** [comment]
the problem statements were taken from BSSPC, there is no enforced guideline on problem statement format

**Comment by espidev** [comment]
so it's not an actual code issue
