### ISSUE TITLE
[BUG] No output specification or sample input/outputs for p10

### ISSUE THREAD

**Issue by potatoeggy** [BayviewComputerClub/smoothie-web#13]
**Describe the bug**
There is no output specification or sample input/output on http://smoothie.bayview.club/problem/p10

Also the URL ends in "p10", while the others are "bsspc2019pX".

**To Reproduce**
1. Visit http://smoothie.bayview.club/problem/p10
2. Scroll down

**Expected behavior**
There should be an output specification, at the very least.

**Screenshots**
![image](https://user-images.githubusercontent.com/25178974/74595768-9bfef700-5013-11ea-8aa4-22f2cf155868.png)
How to solve :(

**Comment by Raymo111** [comment]
P10 is just broken. It will not be fixed at present.
