### ISSUE TITLE
[FR] SSL

### ISSUE THREAD

**Issue by potatoeggy** [BayviewComputerClub/smoothie-web#2]
eNcRyPtIon

**Comment by Raymo111** [comment]
Fixed on CloudFlare

**Comment by Raymo111** [comment]
Apparently cloudflare will break https://bayview.club

**Comment by potatoeggy** [comment]
Why will it break?

Both https://bayview.club and http://bayview.club appear to work properly as of 2020-02-15 on:

- Firefox 72.0.2 (64-bit) with uBlock Origin
- Chromium 79.0.3945.130 (64-bit) with uBlock Origin

The above were only tested on Arch Linux, however.

**Comment by Raymo111** [comment]
When SSL Full (Strict) was enabled on CloudFlare it broke. Right now it's on Flexible, so it doesn't automatically do https rewrites. I'm attempting SSL Full but not strict, hopefully it doesn't break https://bayview.club anymore.

**Comment by Seshpenguin** [comment]
@Raymo111 SSL rewrites need to happen on my nginx not cloudflare.

**Comment by Raymo111** [comment]
@Seshpenguin Can you do that then?

**Comment by Seshpenguin** [comment]
@Raymo111 We left it out for now for debugging purposes. We were having problems with websockets and some other things.

**Comment by Raymo111** [comment]
@Seshpenguin Noted. We'll set this aside then.

**Comment by Raymo111** [comment]
Implemented correctly through cloudflare.
