### ISSUE TITLE
[BUG] Admin pages have no auth

### ISSUE THREAD

**Issue by Raymo111** [BayviewComputerClub/smoothie-web#6]
**Describe the bug**

Admin pages have no auth required. As long as you go to /admin, even without logging in you can access everything.

**To Reproduce**

1. Logout
2. Go to /admin
3. You can access everything.

**Expected behavior**

/admin should 403 and deny access.

**Screenshots**

![image](https://user-images.githubusercontent.com/34818275/74594772-e2e6ef80-5007-11ea-8af0-288ab765b72b.png)

**Additional context**

**Comment by espidev** [comment]
oops I accidentally disabled checking roles when I added the submission perm check

**Comment by espidev** [comment]
this seems to somehow be an issue on smoothie.bayview.club, but not when testing locally?
not totally sure why yet

will have to check out later

**Comment by espidev** [comment]
fixed
