### ISSUE TITLE
[FR] Add favicon

### ISSUE THREAD

**Issue by potatoeggy** [BayviewComputerClub/smoothie-web#8]
**Is your feature request related to a problem? Please describe.**
It looks ugly.

**Describe the solution you'd like**
A nice and pretty icon beside the tab name

**Describe alternatives you've considered**
Have multiple pretty icons beside tab names, but that's not how things work in this world

**Additional context**
![image](https://user-images.githubusercontent.com/25178974/74595525-73293280-5010-11ea-8895-c76374bb3e1f.png)

Look how sad it looks :(

**Comment by Raymo111** [comment]
Added in cbeec16d2f31edc05551d619f4781b982f8b5c5c.
